name: CI

on: [push, pull_request]

jobs:
  default:
    name: Test on ${{ matrix.os }} with node v${{ matrix.node }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install
        env:
          CI: "true"

      - name: Test packages
        run: bun run test
        env:
          CI: "true"
